CRUD_ASP.net/Controllers/ReceiptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_ASP.net.Data;
using CRUD_ASP.net.Models;
using System.Text.Json;
using CRUD_ASP.net.ViewModels;
using NuGet.Protocol;

namespace CRUD_ASP.net.Controllers
{
    public class ReceiptsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<ReceiptsController> _logger;

        public ReceiptsController(ApplicationDbContext context, ILogger<ReceiptsController> logger)
        {
            _logger = logger;
            _context = context;
        }

        // GET: Receipts
        public async Task<IActionResult> Index()
        {

            var listModel = await _context.Receipts
                                    .GroupJoin(
                                        _context.ReceiptDetails,
                                        receipt => receipt.Id,
                                        receiptDetail => receiptDetail.ReceiptId,
                                        (receipt, details) => new
                                        {
                                            Receipt = receipt,
                                            Counted = details.Count()
                                        }
                                    ).ToListAsync();

            var viewModel = listModel.Select(r => new
            {
                r.Receipt.Id,
                r.Receipt.TypeReceipt,
                r.Receipt.ReceiptNumber,
                r.Receipt.Observations,
                r.Receipt.DateEmision,
                r.Receipt.AmountTotal,
                r.Counted // Número de detalles
            }).ToList();

            return View(viewModel);
        }

        // GET: Receipts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (receipt == null)
            {
                return NotFound();
            }

            var ReceiptDetails = await _context.ReceiptDetails.Where(rd => rd.ReceiptId == id).ToListAsync();
            if (receipt == null)
            {
                return NotFound();
            }

            var viewModel = new ReceiptViewModel
            {
                Receipt = receipt,
                ReceiptDetails = ReceiptDetails
            };

            return View(viewModel);
        }

        // GET: Receipts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Receipts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Receipt,ReceiptDetails")] ReceiptViewModel receiptViewModel)
        {
            _context.Receipts.Add(receiptViewModel.Receipt);
            await _context.SaveChangesAsync();

            //var lDetails = JsonSerializer.Deserialize<List<ReceiptDetail>>(receiptViewModel.Receipt);

            try
            {

                foreach (var item in receiptViewModel.ReceiptDetails)
                {
                    item.ReceiptId = receiptViewModel.Receipt.Id;
                    _context.ReceiptDetails.Add(item);
                    await _context.SaveChangesAsync();

                }
                return RedirectToAction("Index");

            }
            catch
            {

                return View(receiptViewModel);
            }

        }

        // GET: Receipts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts.FindAsync(id);
            var ReceiptDetails = await _context.ReceiptDetails.Where(rd => rd.Receipt.Id == id).ToListAsync();
            if (receipt == null)
            {
                return NotFound();
            }

            var viewModel = new ReceiptViewModel
            {
                Receipt = receipt,
                ReceiptDetails = ReceiptDetails
            };

            return View(viewModel);
        }

        // POST: Receipts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Receipt,ReceiptDetails")] ReceiptViewModel receiptViewModel)
        {
            _logger.LogInformation("datas");
            _logger.LogInformation("ReceiptViewModel JSON: {JsonData}", receiptViewModel.ToJson());
            if (id != receiptViewModel.Receipt.Id)
            {
                return NotFound();
            }

            try
            {
                _context.Receipts.Update(receiptViewModel.Receipt);
                await _context.SaveChangesAsync();


                // Bulk update/delete/insert for receipt details
                var existingDetails = _context.ReceiptDetails.Where(rd => rd.ReceiptId == id);
                _context.ReceiptDetails.RemoveRange(existingDetails);
                _logger.LogInformation("datas 2");

                foreach (var item in receiptViewModel.ReceiptDetails)
                {
                    item.ReceiptId = receiptViewModel.Receipt.Id;
                    _context.ReceiptDetails.Add(item);
                }
                _logger.LogInformation("datas 3");

                await _context.SaveChangesAsync();
                _logger.LogInformation("datas 4");

                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ReceiptExists(receiptViewModel.Receipt.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return View(receiptViewModel);
        }

        // GET: Receipts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (receipt == null)
            {
                return NotFound();
            }

            return View(receipt);
        }

        // POST: Receipts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var receipt = await _context.Receipts.FindAsync(id);
            if (receipt != null)
            {
                _context.Receipts.Remove(receipt);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReceiptExists(int id)
        {
            return _context.Receipts.Any(e => e.Id == id);
        }
    }
}

CRUD_ASP.net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_ASP.net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">sqlserver + ASP.NET CORE</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <span class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            @Html.ActionLink("Dashboard", "Index", "Home")
                        </span>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <span class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Facturación
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </span>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                @Html.ActionLink("Facturas", "Index", "Receipts",null,new { @class="nav-link"})
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    ASP.NET CORE + SQLSERVER
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>